rails/config/routes.rb
Code::Application.routes.draw do
  resources :feedbacks

  resources :todos

  resources :tickets do
    collection do
      get 'filter'
    end
  end
  
  resources :milestones
  resources :members
  
  resources :projects do
    resources :milestones
    resources :members
    member do
      get 'admin'
    end
  end
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "signup" => "users#new"
    

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

rails/app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

rails/app/controllers/members_controller.rb
class MembersController < ApplicationController

  def new
    @project = Project.find(session[:project])
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  def index
    @project = Project.find(session[:project])
    @members = @project.members

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end
  
  def create
    @project = Project.find(params[:member][:project_id])
    @user = User.find_by_login(params[:member][:user])
    if @user
      @member = Member.new(:project_id => @project.id, :user_id => @user.id)
      @member.save
      redirect_to admin_project_url(@project)
    else
      render :text => 'user does not exist'
    end
  end

  def destroy
  end
  
end

rails/app/helpers/members_helper.rb
module MembersHelper
end

rails/app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :user_id %><%= f.submit %>
  </div>
<% end %>

rails/app/views/members/index.html.erb
<h1><%=@project.name%>'s members</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Join date</th>
    <th></th>
  </tr>

<% @members.each do |m| %>
  <tr>
    <td><%= User.find(m.user_id).login %></td>
	<td><%= m.created_at %></td>
	<td>
		<%= link_to 'Remove', m, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '+ New Member', new_project_member_path %> |
<%= link_to 'Back to project', project_path(@project) %>

rails/app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', project_members_path(@project) %>