rails/config/routes.rb
Code::Application.routes.draw do
  resources :feedbacks

  resources :todos

  resources :tickets do
    collection do
      get 'filter'
    end
  end
  
  resources :milestones
  resources :members
  
  resources :projects do
    resources :milestones
    resources :members
    member do
      get 'admin'
    end
  end
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "signup" => "users#new"
    

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

rails/app/models/feedback.rb
class Feedback < ActiveRecord::Base
  
  belongs_to :user
end

rails/app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

rails/app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  
end

rails/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :members, :dependent => :destroy
  has_many :users, :through => :members
  
  has_many :tickets, :dependent => :destroy
  has_many :milestones, :dependent => :destroy
  
  def after_save
    @member = self.members.create(:user_id => self.owner)
  end

end

rails/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  
  Priorities = ["Low", "Normal", "High", "Urgent"]
  Statuses = ["New", "Open", "Solved", "Rejected", "Finish"]
  
  def Ticket.filter(project, user, ticket_type)
    querystr = ""
    if user
      querystr.concat("assignee = #{user} AND ")
    end
    
    if ticket_type.to_i == 0
      querystr.concat("ticket_type = 0 AND ")
    else
      querystr.concat("ticket_type = 1 AND ")
    end
    
    querystr.concat("project_id = #{project}")
    @tickets = Ticket.where(querystr)
  end
  
end

rails/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

rails/app/models/user.rb
class User < ActiveRecord::Base

  has_many :members
  has_many :projects, :through => :members
  has_many :todos
  has_many :feedbacks
  
  acts_as_authentic

end

rails/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

rails/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.xml
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.xml
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.xml
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.xml
  def create
    @todo = Todo.new(:content => params[:todo][:content], :user_id => current_user.id)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to(:controller => 'dashboard', :notice => 'Todo was successfully created.') }
#        format.html { redirect_to(@todo, :notice => 'Todo was successfully created.') }
        format.xml  { render :xml => @todo, :status => :created, :location => @todo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.xml
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to(:controller => 'dashboard', :notice => 'Todo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.xml
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => :dashboard) }
      format.xml  { head :ok }
    end
  end
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  layout nil
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default :controller => 'dashboard'
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
    render :layout => 'application'
  end

  def edit
    @user = @current_user
    render :layout => 'application'
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  
  DASHBOARD = 0
  NAV_NEW_PROJECT = -1
  
end

rails/app/helpers/dashboard_helper.rb
module DashboardHelper
end

rails/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

rails/app/helpers/members_helper.rb
module MembersHelper
end

rails/app/helpers/milestones_helper.rb
module MilestonesHelper
end

rails/app/helpers/projects_helper.rb
module ProjectsHelper
end

rails/app/helpers/tickets_helper.rb
module TicketsHelper
end

rails/app/helpers/todos_helper.rb
module TodosHelper
end

rails/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

rails/app/helpers/users_helper.rb
module UsersHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>Code</title>
  <%= stylesheet_link_tag "t" %>
  <%= stylesheet_link_tag "scaffold" %>
  <%= csrf_meta_tag %>
	<link type="text/css" href="/stylesheets/redmond/jquery-ui-1.8.11.custom.css" rel="stylesheet" />	
	<script type="text/javascript" src="/javascripts/jquery-1.5.1.min.js"></script>
	<script type="text/javascript" src="/javascripts/jquery-ui-1.8.11.custom.min.js"></script>
  <%= javascript_include_tag 'rails', 'application' %> 
	<script>
		$(function() {
			function pageHeight(){ 
				if($.browser.msie){ 
				return document.compatMode == "CSS1Compat"? document.documentElement.clientHeight : 
				document.body.clientHeight; 
				}else{ 
				return self.innerHeight; 
				} 
			}; 

			//返回当前页面宽度 
			function pageWidth(){ 
				if($.browser.msie){ 
				return document.compatMode == "CSS1Compat"? document.documentElement.clientWidth : 
				document.body.clientWidth; 
				}else{ 
				return self.innerWidth; 
				} 
			};
			
			$("#ticket-modal").hide();

			$("#ticket-new-btn").click(function() {
				$("#ticket-modal").css('left', function(){
					return (pageWidth() - $("#ticket-modal").width())/2 + "px";
				});
				
				$("#ticket-overlay").height($("#ticket-modal").height() + 10);
				$("#ticket-overlay").width($("#ticket-modal").width() + 20);
				$("#overlay").addClass("overlay");
				$("#ticket-overlay").addClass("ticket-overlay");
				$("#ticket-overlay").css('left', function(){
					return (pageWidth() - $("#ticket-overlay").width())/2 + "px";
				});
				runEffect();
				return false;
			});	
			function runEffect() {
				// most effect types need no options passed by default
				var options = {};
				// run the effect
				$("#ticket-modal").show("blind", options, 500, null);
				$("#ticket-overlay").show("blind", options, 500, null);
			};
		});
	</script>
</head>
<body>
	<div id="overlay"></div>
	<div id="ticket-overlay"></div>
	<div id="ticket-modal" class="ticket-modal">
		<div id="ticket-modal-inner">
			<h1>New Ticket</h1>
			<%= render 'tickets/form' %>
		</div>
	</div>

	<div id="nav">
		<h1 id="logo">ElfTicket</h1>
		<div id="navbar-outer">
			<ul id="navbar">
				<% if session[:nav] == 0%>
					<li class="navbar-item navbar-itemtem-selected">Dashboard</li>
				<%else%>
					<li class="navbar-item"><%=link_to 'Dashboard', :controller => 'dashboard'%></li>
				<%end%>
				<% @projects = User.find(1).projects%>
				<% @projects.each do |p|%>
					<% if session[:nav] == p.id %>
						<li class="navbar-item navbar-item-selected"><%=p.name%></li>
					<%else%>
						<li class="navbar-item"><%=link_to p.name, p%></li>
					<%end%>
				<%end%>
				<% if session[:nav] == -1%>
					<li class="navbar-item navbar-item-selected">+ New Project</li>
				<%else%>
					<li class="navbar-item"><%=link_to "+ New Project", new_project_path%></li>
				<%end%>
			</ul>
		</div>
		<%=link_to current_user.login, account_path, :class=>"navbar-item"%>
		<%=link_to 'Sign out', logout_path, :class => "navbar-item"%>
		<p class="navbar-text">© 2011</p>
		<%=link_to 'feedback', feedbacks_path, :class => "navbar-item"%>
	</div>
	<div id="content">
		<div id="content-inner">
			<%= yield %>
		</div>
	</div>

</body>
</html>