rails/config/routes.rb
Code::Application.routes.draw do
  resources :feedbacks

  resources :todos

  resources :tickets do
    collection do
      get 'filter'
    end
  end
  
  resources :milestones
  resources :members
  
  resources :projects do
    resources :milestones
    resources :members
    member do
      get 'admin'
    end
  end
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "signup" => "users#new"
    

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

rails/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :members, :dependent => :destroy
  has_many :users, :through => :members
  
  has_many :tickets, :dependent => :destroy
  has_many :milestones, :dependent => :destroy
  
  def after_save
    @member = self.members.create(:user_id => self.owner)
  end

end

rails/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'pp'
  
  before_filter :require_user

private
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end
  
public
  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    session[:project] = @project.id
    session[:nav] = @project.id

    pp "session[:user_type] = #{session[:user_type]}, session[:ticket_type] = #{session[:ticket_type]}"
    session[:user_type] = session[:user_type].nil?? 1 : session[:user_type]
    session[:ticket_type] = session[:ticket_type].nil?? 0 : session[:ticket_type]
    pp "session[:user_type] = #{session[:user_type]}, session[:ticket_type] = #{session[:ticket_type]}"
    
    @tickets = Ticket.filter(@project.id, current_user.id, session[:ticket_type])
    @ticket = Ticket.new
    @milestones = @project.milestones
    @members = @project.members

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    session[:nav] = NAV_NEW_PROJECT

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(:name => params[:project][:name], :desc => params[:project][:desc], :owner => current_user.id)
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  
  def admin
    @project = Project.find(params[:id])
    @members = @project.members
    @new_member = Member.new
  end

end

rails/app/helpers/projects_helper.rb
module ProjectsHelper
end

rails/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :rows => 4, :cols => 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/projects/admin.html.erb
<h2>Project Admin</h2>
<h3>Members:</h3>
<% @members.each do |m|%>
	<p><%=User.find(m.user_id).login%></p>
<% end %>
<% form_for @new_member do |f| %>
	<%=f.hidden_field 'project_id', :value => @project.id%>
	<%=f.text_field 'user'%>
	<%=f.submit 'Add Member'%>
<% end %>
<br />

<hr />
<%=link_to "milestones", project_milestones_path(@project)%>
<hr />
<%=link_to "Back to project", @project %>

rails/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>

rails/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.desc %></td>
    <td><%= User.find(project.owner).login %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

rails/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

rails/app/views/projects/show.html.erb
<div class="project-header">
	<h1>Pet Social</h1>
	<p>With electronic outlet GPS, making social with pet</p>
</div>
<hr />
<div class="ticket-new">
	<%=text_field_tag "ticket-title-new", nil, {:class => 'ticket-title-input', :size => 50}%><button id="ticket-new-btn" class="btn">New Ticket</button>
</div>
<br />



<div class="tickets">
	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">
					<div>
						<div class="ticket-top">#23 <a href="">ssyangy</a></div>
						<div class="ticket-content">右上角搜索框用户没输入的情况下应该不能搜索,参见新浪的做法</div>
						<div class="ticket-label">P0 没有会死 xxx 重要 里程碑:6.23</div>
						<div class="ticket-bottom">
							<table border="0" cellpadding="0" cellspacing="0">
							<tbody>
								<tr><td width="110">by: <a href="">truelwl</a></td><td><button>Edit</button></td></tr>
							</tbody>
							</table>
						</div>
					</div>
				</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">
					<div>
						<div class="ticket-top">#23 <a href="">ssyangy</a></div>
						<div class="ticket-content">右上角搜索框用户没输入的情况下应该不能搜索,参见新浪的做法</div>
						<div class="ticket-label">P0 没有会死 xxx 重要 里程碑:6.23</div>
						<div class="ticket-bottom">
							<table border="0" cellpadding="0" cellspacing="0">
							<tbody>
								<tr><td width="110">by: <a href="">truelwl</a></td><td><button>Edit</button></td></tr>
							</tbody>
							</table>
						</div>
					</div>
				</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">
					<div>
						<div class="ticket-top">#23 <a href="">ssyangy</a></div>
						<div class="ticket-content">Use instance_of? in #fields_for to check specifically for a Hash (excluding subclasses)</div>
						<div class="ticket-label">P0 没有会死 xxx 重要 里程碑:6.23</div>
						<div class="ticket-bottom">
							<table border="0" cellpadding="0" cellspacing="0">
							<tbody>
								<tr><td width="110">by: <a href="">truelwl</a></td><td><button>Edit</button></td></tr>
							</tbody>
							</table>
						</div>
					</div>
				</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">content</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">content</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">content</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

	<div class="a-ticket">
	<table width="200" height="250" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td class="top_a"></td>
				<td class="top_b"></td>
				<td class="top_c"><a id="popWindowClosed" href="javascript:c()"><img src="/images/pop_window_closed.png"></a></td>
			</tr>
			<tr>
				<td class="middle_a"></td>
				<td class="middle_b" id="popWindowContent">content</td>
				<td class="middle_c"></td>
			</tr>
			<tr>
				<td class="bottom_a"></td>
				<td class="bottom_b"></td>
				<td class="bottom_c"></td>
			</tr>
		</tbody>
	</table>
	</div>

</div>