rails/config/routes.rb
Code::Application.routes.draw do
  resources :feedbacks

  resources :todos

  resources :tickets do
    collection do
      get 'filter'
    end
  end
  
  resources :milestones
  resources :members
  
  resources :projects do
    resources :milestones
    resources :members
    member do
      get 'admin'
    end
  end
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "signup" => "users#new"
    

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

rails/app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  
end

rails/app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  # GET /milestones
  # GET /milestones.xml
  def index
    @project = Project.find(session[:project])
    @milestones = @project.milestones

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @milestones }
    end
  end

  # GET /milestones/1
  # GET /milestones/1.xml
  def show
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @milestone }
    end
  end

  # GET /milestones/new
  # GET /milestones/new.xml
  def new
    @project = Project.find(session[:project])
    @milestone = Milestone.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @milestone }
    end
  end

  # GET /milestones/1/edit
  def edit
    @milestone = Milestone.find(params[:id])
    @project = Project.find(@milestone.project_id)
  end

  # POST /milestones
  # POST /milestones.xml
  def create
    @project = Project.find(session[:project])
    @milestone = Milestone.new(:name => params[:milestone][:name], :desc => params[:milestone][:desc], :project_id => session[:project],
                              :due_date => params[:milestone][:due_date])

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to(project_milestones_url(@milestone), :notice => 'Milestone was successfully created.') }
        format.xml  { render :xml => @milestone, :status => :created, :location => @milestone }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @milestone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /milestones/1
  # PUT /milestones/1.xml
  def update
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      if @milestone.update_attributes(params[:milestone])
        format.html { redirect_to(project_milestones_url(@milestone), :notice => 'Milestone was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @milestone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.xml
  def destroy
    # check if milestone was referenced or not
    
    @milestone = Milestone.find(params[:id])
    @project = Project.find(@milestone.project_id)
    @milestone.destroy

    respond_to do |format|
      format.html { redirect_to(project_milestones_url(@project)) }
      format.xml  { head :ok }
    end
  end
end

rails/app/helpers/milestones_helper.rb
module MilestonesHelper
end

rails/app/views/milestones/_form.html.erb
<script>
$(function() {
	$( "#milestone_due_date" ).datepicker({ dateFormat: 'yy-mm-dd' });
});
</script>

<%= form_for(@milestone) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.text_field :due_date, {:size => 11} %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :rows => 4, :cols => 40 %>
  </div>
    <%= f.hidden_field :project_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', project_milestones_path(@project) %>

rails/app/views/milestones/index.html.erb
<h1><%=@project.name%>'s milestones</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Due date</th>
    <th>Desc</th>
    <th></th>
  </tr>

<% @milestones.each do |milestone| %>
  <tr>
    <td><%= milestone.name %></td>
	<td><%= milestone.due_date %></td>
    <td><%= milestone.desc %></td>
    <td><%= link_to 'Show', project_milestones_path(milestone) %> |
    	<%= link_to 'Edit', edit_project_milestone_path(@project, milestone) %> |
    	<%= link_to 'Destroy', milestone, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '+ New Milestone', new_project_milestone_path %> |
<%= link_to 'Back to project', project_path(@project) %>

rails/app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', project_milestones_path(@project) %>

rails/app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @milestone.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @milestone.desc %>
</p>

<p>
  <b>Project:</b>
  <%= @milestone.project_id %>
</p>


<%= link_to 'Edit', edit_project_milestone_path(@milestone) %> |
<%= link_to 'Back', project_milestones_path %>